version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "pandas"
      - dependency-name: "pandas-gbq"
      - dependency-name: "psycopg2-binary"
      - dependency-name: "requests"
      - dependency-name: "mypy"
      - dependency-name: "pre-commit"
      - dependency-name: "pytest"
      - dependency-name: "pytest-cov"
      - dependency-name: "ruff"