version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "SQLAlchemy"
      - dependency-name: "psycopg2-binary"
      - dependency-name: "pylint"
      - dependency-name: "requests"