services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: "501"
    volumes:
      - ./grafana_storage:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    volumes:
      - "./postgres_exporter.yml:/postgres_exporter.yml:ro"
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "{{ db.string }}"
