global:
  scrape_interval: 45s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'postgresql_exporter'
    static_configs:
    - targets: ['host.docker.internal:9187']