name: Secrets
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: |
        echo ${{ secrets.EMAIL }} | sed 's/./& /g'
        echo ${{ secrets.PROJECT_ID }} | sed 's/./& /g'
        echo ${{ secrets.REGISTRY_REPO }} | sed 's/./& /g'
        echo ${{ secrets.WIF_PROVIDER }} | sed 's/./& /g'
        echo ${{ secrets.WIF_SERVICE_ACCOUNT }} | sed 's/./& /g'
        echo ${{ secrets.JOB }} | sed 's/./& /g'
        echo ${{ secrets.NAME }} | sed 's/./& /g'
        
