name: Secrets
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: |
        echo ${{ secrets.EMAIL }}
        echo ${{ secrets.PROJECT_ID }}
        echo ${{ secrets.REGISTRY_REPO }}
        echo ${{ secrets.WIF_PROVIDER }}
        echo ${{ secrets.WIF_SERVICE_ACCOUNT }}
        echo ${{ secrets.JOB }}
        echo ${{ secrets.NAME }}
        
