name: Pytest

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info

  push:
    paths-ignore:
      - '.github/**'
      - 'api/**'
      - 'etl/**'
      - 'cli/**'
      - 'components/**'
      - 'dbt_production/**'
      - 'prefect/**'
      - 'soda/**'
      - 'terraform/**'
      - 'tests/**'
      - 'CHANGELOG.md'
      - '.dockerignore'
      - '.gitignore'
      - '.prefectignore'
      - '.pre-commit-config.yaml'
      - '.streamlit'
      - 'pyproject.toml'
      - 'README.md'
    branches:
      - "main"

jobs:
    pytest:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: 3.11.6

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install google-cloud-bigquery
                pip unstall firebase-admin
                pip install plotly
                pip install streamlit
                pip install pytest==7.4.3
                pip install pytest-cov==4.1.0

            - name: Google Auth
              id: auth
              uses: 'google-github-actions/auth@v1'
              with:
                token_format: 'access_token'
                workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
                service_account: '${{ secrets.WIF_SERVICE_ACCOUNT_DATABASE }}'
                project_id: '${{ secrets.PROJECT_ID }}'

            - name: Run Tests
              run: |
                pytest --cov=streamlit_app tests/ -v